### ISSUE TITLE
#Issue in Grove.Data

### ISSUE THREAD

**Issue by JakubSzatybelko** [norbertszsor/Grove.Web#1]
I've noticed you are using c# to build this project, have you consider using something better ? i can highly recommend PHP or Python 😄

**Comment by norbertszsor** [comment]
![662df9530f5e8c0e99a1fcfa648baee1](https://github.com/norbertszsor/GroveWeb/assets/47736350/5fd2468d-dda2-465f-a344-cfcc62319af7)
